jobs:
  provision-ec2:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
  
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}'
          aws-region: ap-south-1
  run: |
   cd aws/
   ansble-playbook main.yml 
